// ═══════════════════════════════════════════════════
// DATEN – Alle Vokabeln Lektion 1–18
// ═══════════════════════════════════════════════════

const ALL_VOCAB = [
  // Lektion 1
  { id:'l01_01', latin:'amīca',      german:'die Freundin' },
  { id:'l01_02', latin:'amīcus',     german:'der Freund' },
  { id:'l01_03', latin:'clāmāre',    german:'schreien, rufen' },
  { id:'l01_04', latin:'cōgitāre',   german:'nachdenken, überlegen' },
  { id:'l01_05', latin:'cūr?',       german:'warum?' },
  { id:'l01_06', latin:'dēbēre',     german:'müssen, schulden' },
  { id:'l01_07', latin:'domina',     german:'die Herrin' },
  { id:'l01_08', latin:'dominus',    german:'der Herr' },
  { id:'l01_09', latin:'est',        german:'ist (er/sie/es)' },
  { id:'l01_10', latin:'et',         german:'und' },
  { id:'l01_11', latin:'familia',    german:'die Familie' },
  { id:'l01_12', latin:'gaudēre',    german:'sich freuen' },
  { id:'l01_13', latin:'gaudium',    german:'die Freude' },
  { id:'l01_14', latin:'hīc',        german:'hier' },
  { id:'l01_15', latin:'hodiē',      german:'heute' },
  { id:'l01_16', latin:'iam',        german:'schon, jetzt' },
  { id:'l01_17', latin:'labōrāre',   german:'arbeiten' },
  { id:'l01_18', latin:'nam',        german:'nämlich, denn' },
  { id:'l01_19', latin:'nārrāre',    german:'erzählen, berichten' },
  { id:'l01_20', latin:'nōn',        german:'nicht' },
  { id:'l01_21', latin:'pārēre',     german:'gehorchen, folgen' },
  { id:'l01_22', latin:'placēre',    german:'gefallen' },
  { id:'l01_23', latin:'properāre',  german:'sich beeilen' },
  { id:'l01_24', latin:'sed',        german:'aber, sondern' },
  { id:'l01_25', latin:'semper',     german:'immer' },
  { id:'l01_26', latin:'serva',      german:'die Sklavin' },
  { id:'l01_27', latin:'servus',     german:'der Sklave' },
  { id:'l01_28', latin:'sunt',       german:'sind (sie)' },
  { id:'l01_29', latin:'tum',        german:'dann, darauf' },
  { id:'l01_30', latin:'ubī?',       german:'wo?' },
  { id:'l01_31', latin:'venīre',     german:'kommen' },
  { id:'l01_32', latin:'verbum',     german:'das Wort' },
  // Lektion 2
  { id:'l02_01', latin:'audīre',          german:'hören' },
  { id:'l02_02', latin:'bene',            german:'gut, wohl' },
  { id:'l02_03', latin:'convenīre',       german:'zusammenkommen' },
  { id:'l02_04', latin:'ego',             german:'ich' },
  { id:'l02_05', latin:'epistula',        german:'der Brief' },
  { id:'l02_06', latin:'exspectāre',      german:'erwarten, abwarten' },
  { id:'l02_07', latin:'fābula',          german:'die Erzählung, Fabel' },
  { id:'l02_08', latin:'forās',           german:'hinaus, nach draußen' },
  { id:'l02_09', latin:'intrāre',         german:'eintreten, hineingehen' },
  { id:'l02_10', latin:'laudāre',         german:'loben' },
  { id:'l02_11', latin:'libenter',        german:'gern, bereitwillig' },
  { id:'l02_12', latin:'manēre',          german:'bleiben, warten' },
  { id:'l02_13', latin:'monēre',          german:'mahnen, ermahnen' },
  { id:'l02_14', latin:'nescīre',         german:'nicht wissen' },
  { id:'l02_15', latin:'nunc',            german:'jetzt, nun' },
  { id:'l02_16', latin:'quid?',           german:'was?' },
  { id:'l02_17', latin:'rogāre',          german:'fragen, bitten' },
  { id:'l02_18', latin:'salūtāre',        german:'begrüßen, grüßen' },
  { id:'l02_19', latin:'salvē!',          german:'sei gegrüßt! (Sg.)' },
  { id:'l02_20', latin:'salvēte!',        german:'seid gegrüßt! (Pl.)' },
  { id:'l02_21', latin:'statim',          german:'sofort, sogleich' },
  { id:'l02_22', latin:'studēre',         german:'sich bemühen, eifrig sein' },
  { id:'l02_23', latin:'subitō',          german:'plötzlich' },
  { id:'l02_24', latin:'tabula',          german:'die Tafel, das Brett' },
  { id:'l02_25', latin:'tacēre',          german:'schweigen, still sein' },
  { id:'l02_26', latin:'timēre',          german:'fürchten, sich fürchten' },
  { id:'l02_27', latin:'tū',              german:'du' },
  { id:'l02_28', latin:'venia',           german:'die Gnade, Verzeihung' },
  { id:'l02_29', latin:'vidēre',          german:'sehen' },
  // Lektion 3
  { id:'l03_01', latin:'accēdere',        german:'sich nähern, herantreten' },
  { id:'l03_02', latin:'capere',          german:'fassen, nehmen, ergreifen' },
  { id:'l03_03', latin:'cessāre',         german:'zögern, untätig sein' },
  { id:'l03_04', latin:'clam',            german:'heimlich, verborgen' },
  { id:'l03_05', latin:'clāmor',          german:'das Geschrei, der Lärm' },
  { id:'l03_06', latin:'cupere',          german:'wünschen, begehren' },
  { id:'l03_07', latin:'currere',         german:'laufen, eilen' },
  { id:'l03_08', latin:'dīcere',          german:'sagen, nennen, sprechen' },
  { id:'l03_09', latin:'diū',             german:'lange (Zeit)' },
  { id:'l03_10', latin:'ecce!',           german:'sieh! schau! da!' },
  { id:'l03_11', latin:'fugere',          german:'fliehen, fliegen' },
  { id:'l03_12', latin:'fūr',             german:'der Dieb' },
  { id:'l03_13', latin:'habēre',          german:'haben, halten' },
  { id:'l03_14', latin:'ibī',             german:'dort, da' },
  { id:'l03_15', latin:'ita',             german:'so, auf diese Weise' },
  { id:'l03_16', latin:'nōn dēbēre',      german:'nicht dürfen, nicht sollen' },
  { id:'l03_17', latin:'ōrātor',          german:'der Redner' },
  { id:'l03_18', latin:'petere',          german:'suchen, verlangen, bitten' },
  { id:'l03_19', latin:'populus',         german:'das Volk' },
  { id:'l03_20', latin:'quaerere',        german:'suchen, fragen' },
  { id:'l03_21', latin:'rapere',          german:'rauben, fortreißen' },
  { id:'l03_22', latin:'relinquere',      german:'zurücklassen, verlassen' },
  { id:'l03_23', latin:'saepe',           german:'oft, häufig' },
  { id:'l03_24', latin:'sōl',             german:'die Sonne' },
  { id:'l03_25', latin:'tenēre',          german:'halten, festhalten' },
  { id:'l03_26', latin:'ubīque',          german:'überall' },
  { id:'l03_27', latin:'vocāre',          german:'rufen, nennen' },
  // Lektion 4
  { id:'l04_01', latin:'adesse',          german:'anwesend sein, helfen' },
  { id:'l04_02', latin:'amīcitia',        german:'die Freundschaft' },
  { id:'l04_03', latin:'certē',           german:'sicher, gewiss, bestimmt' },
  { id:'l04_04', latin:'cōnsistere',      german:'stehen bleiben, sich aufstellen' },
  { id:'l04_05', latin:'esse',            german:'sein, existieren' },
  { id:'l04_06', latin:'etiam',           german:'auch, sogar, noch' },
  { id:'l04_07', latin:'frūstrā',         german:'vergeblich, umsonst' },
  { id:'l04_08', latin:'habitāre',        german:'wohnen, bewohnen' },
  { id:'l04_09', latin:'invenīre',        german:'finden, entdecken' },
  { id:'l04_10', latin:'līberī',          german:'die Kinder' },
  { id:'l04_11', latin:'licet',           german:'es ist erlaubt, man darf' },
  { id:'l04_12', latin:'meherc(u)le!',    german:'bei Herkules! wahrhaftig!' },
  { id:'l04_13', latin:'mox',             german:'bald, gleich' },
  { id:'l04_14', latin:'nōn iam',         german:'nicht mehr' },
  { id:'l04_15', latin:'parentēs',        german:'die Eltern' },
  { id:'l04_16', latin:'perīculum',       german:'die Gefahr' },
  { id:'l04_17', latin:'posse',           german:'können, vermögen' },
  { id:'l04_18', latin:'quis?',           german:'wer?' },
  { id:'l04_19', latin:'respondēre',      german:'antworten, erwidern' },
  { id:'l04_20', latin:'scelerātus',      german:'ruchlos, verbrecherisch; Schurke' },
  { id:'l04_21', latin:'scīre',           german:'wissen, kennen' },
  { id:'l04_22', latin:'sōlum',           german:'nur, allein, bloß' },
  { id:'l04_23', latin:'tandem',          german:'endlich, schließlich' },
  { id:'l04_24', latin:'via',             german:'der Weg, die Straße' },
  { id:'l04_25', latin:'vīcus',           german:'der Ort, das Dorf, die Gasse' },
  { id:'l04_26', latin:'vix',             german:'kaum, mit Mühe' },
  // Lektion 5
  { id:'l05_01', latin:'animus',          german:'der Sinn, der Mut, die Seele' },
  { id:'l05_02', latin:'ārdēre',          german:'brennen, glühen, leuchten' },
  { id:'l05_03', latin:'āvertere',        german:'abwenden, ablenken' },
  { id:'l05_04', latin:'cantāre',         german:'singen, spielen' },
  { id:'l05_05', latin:'cīvis',           german:'der Bürger, die Bürgerin' },
  { id:'l05_06', latin:'dēlectāre',       german:'erfreuen, ergötzen' },
  { id:'l05_07', latin:'dēsīderāre',      german:'vermissen, sich sehnen nach' },
  { id:'l05_08', latin:'docēre',          german:'lehren, unterrichten' },
  { id:'l05_09', latin:'dolor',           german:'der Schmerz, das Leid' },
  { id:'l05_10', latin:'et … et …',       german:'sowohl … als auch …' },
  { id:'l05_11', latin:'fīlia',           german:'die Tochter' },
  { id:'l05_12', latin:'fīlius',          german:'der Sohn' },
  { id:'l05_13', latin:'homō',            german:'der Mensch' },
  { id:'l05_14', latin:'hōra',            german:'die Stunde' },
  { id:'l05_15', latin:'incipere',        german:'beginnen, anfangen' },
  { id:'l05_16', latin:'lūdus',           german:'das Spiel, die Schule' },
  { id:'l05_17', latin:'māter',           german:'die Mutter' },
  { id:'l05_18', latin:'mors',            german:'der Tod' },
  { id:'l05_19', latin:'oculus',          german:'das Auge' },
  { id:'l05_20', latin:'pater',           german:'der Vater' },
  { id:'l05_21', latin:'plācāre',         german:'besänftigen, versöhnen' },
  { id:'l05_22', latin:'poēta',           german:'der Dichter' },
  { id:'l05_23', latin:'pūgna',           german:'der Kampf, das Gefecht' },
  { id:'l05_24', latin:'soror',           german:'die Schwester' },
  { id:'l05_25', latin:'spectāre',        german:'anschauen, betrachten, zusehen' },
  { id:'l05_26', latin:'turba',           german:'die Menge, der Tumult' },
  { id:'l05_27', latin:'uxor',            german:'die Ehefrau' },
  // Lektion 6
  { id:'l06_01', latin:'abundāre',        german:'reich sein an, überfließen' },
  { id:'l06_02', latin:'auxilium',        german:'die Hilfe, der Beistand' },
  { id:'l06_03', latin:'bibere',          german:'trinken' },
  { id:'l06_04', latin:'carmen',          german:'das Lied, das Gedicht' },
  { id:'l06_05', latin:'cēna',            german:'das Abendessen, Gastmahl' },
  { id:'l06_06', latin:'cēnāre',          german:'zu Abend essen' },
  { id:'l06_07', latin:'cibus',           german:'die Speise, das Essen' },
  { id:'l06_08', latin:'complēre',        german:'füllen, anfüllen, vollenden' },
  { id:'l06_09', latin:'dormīre',         german:'schlafen' },
  { id:'l06_10', latin:'enim',            german:'nämlich, denn (nachgestellt)' },
  { id:'l06_11', latin:'equus',           german:'das Pferd' },
  { id:'l06_12', latin:'frāter',          german:'der Bruder' },
  { id:'l06_13', latin:'gladius',         german:'das Schwert' },
  { id:'l06_14', latin:'hospes',          german:'der Gastfreund, der Gast' },
  { id:'l06_15', latin:'hostis',          german:'der Feind' },
  { id:'l06_16', latin:'intereā',         german:'inzwischen, unterdessen' },
  { id:'l06_17', latin:'līberāre',        german:'befreien, erlösen' },
  { id:'l06_18', latin:'portāre',         german:'tragen, bringen' },
  { id:'l06_19', latin:'repellere',       german:'zurückstoßen, abwehren' },
  { id:'l06_20', latin:'rīdēre',          german:'lachen' },
  { id:'l06_21', latin:'sermō',           german:'die Unterhaltung, Rede' },
  { id:'l06_22', latin:'timor',           german:'die Furcht' },
  { id:'l06_23', latin:'tot',             german:'so viele (indeklinabel)' },
  { id:'l06_24', latin:'vacāre',          german:'frei sein von, leer sein' },
  { id:'l06_25', latin:'vincere',         german:'besiegen, überwinden' },
  { id:'l06_26', latin:'vīnum',           german:'der Wein' },
  // Lektion 7
  { id:'l07_01', latin:'ā/ab',            german:'von … weg, durch (m. Abl.)' },
  { id:'l07_02', latin:'ad',              german:'zu, an, bei (m. Akk.)' },
  { id:'l07_03', latin:'ante',            german:'vor, vorher (m. Akk.)' },
  { id:'l07_04', latin:'āra',             german:'der Altar' },
  { id:'l07_05', latin:'colere',          german:'bebauen, pflegen, verehren' },
  { id:'l07_06', latin:'crās',            german:'morgen' },
  { id:'l07_07', latin:'cum',             german:'mit, zusammen mit (m. Abl.)' },
  { id:'l07_08', latin:'dē',              german:'von, über, herab (m. Abl.)' },
  { id:'l07_09', latin:'dea',             german:'die Göttin' },
  { id:'l07_10', latin:'deus',            german:'der Gott' },
  { id:'l07_11', latin:'dūcere',          german:'führen, leiten' },
  { id:'l07_12', latin:'ē/ex',            german:'aus, heraus aus (m. Abl.)' },
  { id:'l07_13', latin:'ergō',            german:'also, folglich, daher' },
  { id:'l07_14', latin:'facere',          german:'machen, tun' },
  { id:'l07_15', latin:'forum',           german:'der Marktplatz, das Forum' },
  { id:'l07_16', latin:'in (m. Abl.)',    german:'in, an (Wo? – Lage)' },
  { id:'l07_17', latin:'in (m. Akk.)',    german:'in, nach (Richtung)' },
  { id:'l07_18', latin:'inter',           german:'zwischen, unter (m. Akk.)' },
  { id:'l07_19', latin:'iuvenis',         german:'junger Mann, junge Frau' },
  { id:'l07_20', latin:'latēre',          german:'verborgen sein, sich verbergen' },
  { id:'l07_21', latin:'ōrāre',           german:'bitten, beten' },
  { id:'l07_22', latin:'per',             german:'durch, hindurch (m. Akk.)' },
  { id:'l07_23', latin:'post',            german:'nach, hinter (m. Akk.)' },
  { id:'l07_24', latin:'prō',             german:'für, vor, anstatt (m. Abl.)' },
  { id:'l07_25', latin:'sacerdōs',        german:'der Priester, die Priesterin' },
  { id:'l07_26', latin:'sacrum',          german:'das Heiligtum, das Opfer' },
  { id:'l07_27', latin:'salūs',           german:'Heil, Rettung, das Wohl' },
  { id:'l07_28', latin:'templum',         german:'der Tempel' },
  // Lektion 8
  { id:'l08_01', latin:'ager',            german:'das Feld, der Acker' },
  { id:'l08_02', latin:'arma',            german:'die Waffen, die Rüstung' },
  { id:'l08_03', latin:'bonus',           german:'gut, tüchtig, brav' },
  { id:'l08_04', latin:'cavēre',          german:'aufpassen, sich hüten vor' },
  { id:'l08_05', latin:'citō',            german:'schnell, eilig' },
  { id:'l08_06', latin:'cōnsilium',       german:'der Rat, der Plan' },
  { id:'l08_07', latin:'contentus',       german:'zufrieden, begnügt' },
  { id:'l08_08', latin:'continēre',       german:'zusammenhalten, enthalten' },
  { id:'l08_09', latin:'cūria',           german:'die Kurie, Ratsversammlung' },
  { id:'l08_10', latin:'improbus',        german:'schlecht, ruchlos, unredlich' },
  { id:'l08_11', latin:'incendere',       german:'anzünden, entflammen' },
  { id:'l08_12', latin:'inimīcus',        german:'der Feind, feindlich' },
  { id:'l08_13', latin:'līber',           german:'frei, unabhängig' },
  { id:'l08_14', latin:'māgnus',          german:'groß, bedeutend' },
  { id:'l08_15', latin:'malus',           german:'schlecht, böse' },
  { id:'l08_16', latin:'miser',           german:'elend, unglücklich, armselig' },
  { id:'l08_17', latin:'multī',           german:'viele' },
  { id:'l08_18', latin:'parvus',          german:'klein, gering' },
  { id:'l08_19', latin:'pergere',         german:'fortfahren, weitergehen' },
  { id:'l08_20', latin:'porta',           german:'das Tor, die Tür' },
  { id:'l08_21', latin:'puella',          german:'das Mädchen' },
  { id:'l08_22', latin:'puer',            german:'der Junge, der Knabe' },
  { id:'l08_23', latin:'pulcher',         german:'schön, prächtig' },
  { id:'l08_24', latin:'sors',            german:'das Los, das Schicksal' },
  { id:'l08_25', latin:'tantum',          german:'nur, so viel, bloß' },
  { id:'l08_26', latin:'urbs',            german:'die Stadt' },
  { id:'l08_27', latin:'vir',             german:'der Mann' },
  { id:'l08_28', latin:'vīta',            german:'das Leben' },
  // Lektion 9
  { id:'l09_01', latin:'adhibēre',        german:'hinzuziehen, anwenden, gebrauchen' },
  { id:'l09_02', latin:'aedificāre',      german:'bauen, errichten' },
  { id:'l09_03', latin:'atque/ac',        german:'und, und auch, und zwar' },
  { id:'l09_04', latin:'dēnique',         german:'schließlich, endlich, kurz' },
  { id:'l09_05', latin:'dolus',           german:'der Betrug, die List' },
  { id:'l09_06', latin:'fēmina',          german:'die Frau' },
  { id:'l09_07', latin:'grātia',          german:'die Anmut, der Dank, die Gunst' },
  { id:'l09_08', latin:'īnsula',          german:'die Insel, das Mietshaus' },
  { id:'l09_09', latin:'iterum',          german:'wieder, nochmals' },
  { id:'l09_10', latin:'laetus',          german:'fröhlich, freudig, glücklich' },
  { id:'l09_11', latin:'locāre',          german:'anstellen, vermieten, platzieren' },
  { id:'l09_12', latin:'mandāre',         german:'anvertrauen, befehlen, beauftragen' },
  { id:'l09_13', latin:'numquam',         german:'niemals, nie' },
  { id:'l09_14', latin:'ostendere',       german:'zeigen, offenbaren, vorweisen' },
  { id:'l09_15', latin:'profectō',        german:'fürwahr, gewiss, tatsächlich' },
  { id:'l09_16', latin:'prohibēre',       german:'hindern, verhindern, fernhalten' },
  { id:'l09_17', latin:'quī',             german:'der, welcher (Relativpronomen)' },
  { id:'l09_18', latin:'quidem',          german:'zwar, freilich, jedenfalls' },
  { id:'l09_19', latin:'ruere',           german:'stürzen, eilen, hineinstürzen' },
  { id:'l09_20', latin:'sine',            german:'ohne (m. Abl.)' },
  { id:'l09_21', latin:'situs',           german:'gelegen, befindlich; die Lage' },
  { id:'l09_22', latin:'superbus',        german:'stolz, hochmütig, überheblich' },
  { id:'l09_23', latin:'vērus',           german:'wahr, wirklich, echt' },
  { id:'l09_24', latin:'vestis',          german:'das Gewand, die Kleidung' },
  { id:'l09_25', latin:'vōx',             german:'die Stimme, der Ruf, das Wort' },
  // Lektion 10
  { id:'l10_01', latin:'accipere',        german:'empfangen, annehmen, erfahren' },
  { id:'l10_02', latin:'ācer',            german:'scharf, heftig, tüchtig' },
  { id:'l10_03', latin:'celer',           german:'schnell, flink, rasch' },
  { id:'l10_04', latin:'clārus',          german:'hell, berühmt, klar' },
  { id:'l10_05', latin:'cūra',            german:'die Sorge, die Mühe, die Pflege' },
  { id:'l10_06', latin:'dōnāre',          german:'schenken, beschenken' },
  { id:'l10_07', latin:'fēlīx, fēlīcis',      german:'glücklich, günstig' },
  { id:'l10_08', latin:'fortis',          german:'stark, tapfer, mutig' },
  { id:'l10_09', latin:'incolumis',       german:'unversehrt, wohlbehalten, sicher' },
  { id:'l10_10', latin:'ingēns, ingentis',      german:'riesig, gewaltig' },
  { id:'l10_11', latin:'intellegere',     german:'verstehen, erkennen, einsehen' },
  { id:'l10_12', latin:'īra',             german:'der Zorn, die Wut' },
  { id:'l10_13', latin:'iuvāre',          german:'helfen, erfreuen, nützen' },
  { id:'l10_14', latin:'legere',          german:'lesen, sammeln, auswählen' },
  { id:'l10_15', latin:'levis',           german:'leicht, gering, unbedeutend' },
  { id:'l10_16', latin:'nihil',           german:'nichts' },
  { id:'l10_17', latin:'nox',             german:'die Nacht' },
  { id:'l10_18', latin:'omnis',           german:'jeder, alle, ganz' },
  { id:'l10_19', latin:'pecūnia',         german:'das Geld, das Vermögen' },
  { id:'l10_20', latin:'plēnus',          german:'voll, reich an' },
  { id:'l10_21', latin:'potēns, potentis',      german:'mächtig, vermögend' },
  { id:'l10_22', latin:'praemium',        german:'die Belohnung, der Lohn, der Preis' },
  { id:'l10_23', latin:'prūdēns, prūdentis',      german:'klug, einsichtig' },
  { id:'l10_24', latin:'tēctum',          german:'das Dach, das Haus, das Dach' },
  { id:'l10_25', latin:'turpis',          german:'hässlich, schändlich, schmachvoll' },
  { id:'l10_26', latin:'unde?',           german:'woher?' },
  { id:'l10_27', latin:'vehemēns, vehementis',      german:'heftig, leidenschaftlich' },
  { id:'l10_28', latin:'vīs',             german:'die Kraft, die Gewalt, die Macht' },
  // Lektion 11
  { id:'l11_01', latin:'aliquandō',       german:'einmal, irgendwann, manchmal' },
  { id:'l11_02', latin:'annus',           german:'das Jahr' },
  { id:'l11_03', latin:'audācia',         german:'Kühnheit, Mut, Dreistigkeit' },
  { id:'l11_04', latin:'cīvitās',         german:'die Bürgerschaft, der Staat' },
  { id:'l11_05', latin:'comes',           german:'der Begleiter, die Begleiterin' },
  { id:'l11_06', latin:'cōnsul',          german:'der Konsul' },
  { id:'l11_07', latin:'custōs',          german:'der Wächter, der Hüter' },
  { id:'l11_08', latin:'dēfendere',       german:'verteidigen, abwehren, schützen' },
  { id:'l11_09', latin:'domī',            german:'zu Hause (Ortsangabe)' },
  { id:'l11_10', latin:'ēripere',         german:'entreißen, befreien, retten' },
  { id:'l11_11', latin:'impedīre',        german:'hindern, hemmen, erschweren' },
  { id:'l11_12', latin:'itaque',          german:'und so, daher, deshalb' },
  { id:'l11_13', latin:'mē',              german:'mich (Akk. von ego)' },
  { id:'l11_14', latin:'mihī',            german:'mir (Dat. von ego)' },
  { id:'l11_15', latin:'necāre',          german:'töten, umbringen' },
  { id:'l11_16', latin:'nōnnūllī',        german:'einige, manche' },
  { id:'l11_17', latin:'ōrātiō',          german:'die Rede, die Ansprache' },
  { id:'l11_18', latin:'parāre',          german:'vorbereiten, beschaffen, s. anschicken' },
  { id:'l11_19', latin:'pellere',         german:'stoßen, vertreiben, treiben' },
  { id:'l11_20', latin:'=-que',           german:'und (angehängtes Enklitikon)' },
  { id:'l11_21', latin:'nē … quidem',     german:'nicht einmal' },
  { id:'l11_22', latin:'sub',             german:'unter, unterhalb (m. Abl.)' },
  { id:'l11_23', latin:'tibi',            german:'dir (Dat. von tū)' },
  { id:'l11_24', latin:'ūniversus',       german:'ganz, sämtlich, insgesamt' },
  { id:'l11_25', latin:'valdē',           german:'sehr, stark, außerordentlich' },
  { id:'l11_26', latin:'vīvere',          german:'leben' },
  // Lektion 12
  { id:'l12_01', latin:'accūsāre',        german:'anklagen, beschuldigen' },
  { id:'l12_02', latin:'agere',           german:'tun, treiben, handeln' },
  { id:'l12_03', latin:'appārēre',        german:'erscheinen, sichtbar werden' },
  { id:'l12_04', latin:'creāre',          german:'erschaffen, hervorbringen, wählen' },
  { id:'l12_05', latin:'crēdere',         german:'glauben, vertrauen' },
  { id:'l12_06', latin:'dēserere',        german:'verlassen, im Stich lassen' },
  { id:'l12_07', latin:'dēsinere',        german:'aufhören, zu Ende gehen' },
  { id:'l12_08', latin:'dolēre',          german:'leiden, schmerzen, betrübt sein' },
  { id:'l12_09', latin:'dūrus',           german:'hart, schwer, streng, rau' },
  { id:'l12_10', latin:'exilium',         german:'die Verbannung, das Exil' },
  { id:'l12_11', latin:'fīdus',           german:'treu, zuverlässig, vertrauenswürdig' },
  { id:'l12_12', latin:'iūdicium',        german:'das Urteil, das Gericht, das Verfahren' },
  { id:'l12_13', latin:'lacrima',         german:'die Träne' },
  { id:'l12_14', latin:'memoria',         german:'die Erinnerung, das Gedächtnis' },
  { id:'l12_15', latin:'memoriā tenēre',  german:'im Gedächtnis behalten, auswendig wissen' },
  { id:'l12_16', latin:'mortuus',         german:'tot, gestorben' },
  { id:'l12_17', latin:'patrēs',          german:'die Väter, die Senatoren, die Vorfahren' },
  { id:'l12_18', latin:'patria',          german:'die Heimat, das Vaterland' },
  { id:'l12_19', latin:'prōdere',         german:'verraten, preisgeben, überliefern' },
  { id:'l12_20', latin:'quantopere',      german:'wie sehr, in welchem Maße' },
  { id:'l12_21', latin:'quia',            german:'weil, da' },
  { id:'l12_22', latin:'quotiēns',        german:'so oft wie, sooft' },
  { id:'l12_23', latin:'servāre',         german:'bewahren, retten, beschützen' },
  { id:'l12_24', latin:'sollicitāre',     german:'beunruhigen, aufwühlen, antreiben' },
  { id:'l12_25', latin:'tamen',           german:'dennoch, trotzdem, jedoch' },
  { id:'l12_26', latin:'tempus',          german:'die Zeit, der Zeitpunkt' },
  { id:'l12_27', latin:'virtūs',          german:'die Tugend, die Tüchtigkeit, der Mut' },
  { id:'l12_28', latin:'vitium',          german:'der Fehler, das Laster, der Mangel' },
  // Lektion 13
  { id:'l13_01', latin:'autem',           german:'aber, jedoch, dagegen (nachgestellt)' },
  { id:'l13_02', latin:'cārus',           german:'lieb, teuer, wertvoll' },
  { id:'l13_03', latin:'convenīre',       german:'zusammenkommen, passen, übereinstimmen' },
  { id:'l13_04', latin:'convīvium',       german:'das Gastmahl, das Festessen' },
  { id:'l13_05', latin:'crūdēlis',        german:'grausam, herzlos' },
  { id:'l13_06', latin:'cūrāre',          german:'sorgen für, pflegen, s. kümmern um' },
  { id:'l13_07', latin:'dare',            german:'geben, schenken, gewähren' },
  { id:'l13_08', latin:'decet',           german:'es ziemt sich, es geziemt' },
  { id:'l13_09', latin:'dēesse',          german:'fehlen, mangeln, im Stich lassen' },
  { id:'l13_10', latin:'dīligēns',        german:'fleißig, sorgfältig (Gen. dīligentis)' },
  { id:'l13_11', latin:'haud',            german:'(gar) nicht, keineswegs' },
  { id:'l13_12', latin:'is',              german:'er, dieser, jener (Demonstrativpronomen)' },
  { id:'l13_13', latin:'iubēre',          german:'befehlen, beauftragen, anordnen' },
  { id:'l13_14', latin:'iūcundus',        german:'angenehm, erfreulich, liebenswürdig' },
  { id:'l13_15', latin:'labor',           german:'die Arbeit, die Mühe, die Anstrengung' },
  { id:'l13_16', latin:'liber',           german:'das Buch' },
  { id:'l13_17', latin:'nōs',             german:'wir, uns (1. Pers. Pl.)' },
  { id:'l13_18', latin:'ōtium',           german:'die Muße, die Freizeit, der Friede' },
  { id:'l13_19', latin:'posteā',          german:'danach, nachher, später' },
  { id:'l13_20', latin:'quoque',          german:'auch, ebenfalls (nachgestellt)' },
  { id:'l13_21', latin:'scrībere',        german:'schreiben' },
  { id:'l13_22', latin:'servīre',         german:'dienen, Sklave sein' },
  { id:'l13_23', latin:'servitūs',        german:'die Sklaverei, die Knechtschaft' },
  { id:'l13_24', latin:'tam',             german:'so, ebenso (bei Adjektiven)' },
  { id:'l13_25', latin:'velut',           german:'wie, gleichwie, so wie' },
  { id:'l13_26', latin:'vōs',             german:'ihr, euch (2. Pers. Pl.)' },
  // Lektion 14
  { id:'l14_01', latin:'āctio',           german:'Handlung, Tat; Klage' },
  { id:'l14_02', latin:'anteā',           german:'vorher, früher, zuvor' },
  { id:'l14_03', latin:'aspicere',        german:'anblicken, betrachten, ansehen' },
  { id:'l14_04', latin:'caedere',         german:'hauen, schlagen, töten' },
  { id:'l14_05', latin:'causa',           german:'der Grund, die Ursache, der Fall' },
  { id:'l14_06', latin:'committere',      german:'anvertrauen, begehen, liefern' },
  { id:'l14_07', latin:'comprehendere',   german:'ergreifen, festnehmen, begreifen' },
  { id:'l14_08', latin:'damnāre',         german:'verurteilen (m. Gen. der Strafe)' },
  { id:'l14_09', latin:'fīnīre',          german:'beenden, abgrenzen, bestimmen' },
  { id:'l14_10', latin:'interficere',     german:'töten, umbringen, vernichten' },
  { id:'l14_11', latin:'īrātus',          german:'zornig, aufgebracht, wütend' },
  { id:'l14_12', latin:'iūdex',           german:'der Richter' },
  { id:'l14_13', latin:'iūstus',          german:'gerecht, rechtmäßig, rechtschaffen' },
  { id:'l14_14', latin:'mīles',           german:'der Soldat, der Krieger' },
  { id:'l14_15', latin:'paulō',           german:'ein wenig, um ein bisschen (Abl.)' },
  { id:'l14_16', latin:'paulum',          german:'ein wenig, etwas, ein bisschen' },
  { id:'l14_17', latin:'poena',           german:'die Strafe, die Buße, die Sühne' },
  { id:'l14_18', latin:'praeclārus',      german:'sehr berühmt, hervorragend, glänzend' },
  { id:'l14_19', latin:'probus',          german:'rechtschaffen, tüchtig, redlich' },
  { id:'l14_20', latin:'propter',         german:'wegen, aufgrund von (m. Akk.)' },
  { id:'l14_21', latin:'scelus',          german:'das Verbrechen, Untat, die Schlechtigkeit' },
  { id:'l14_22', latin:'stāre',           german:'stehen, stillstehen, feststehen' },
  { id:'l14_23', latin:'suscipere',       german:'übernehmen, auf sich nehmen, unternehmen' },
  { id:'l14_24', latin:'tantus',          german:'so groß, so bedeutend' },
  { id:'l14_25', latin:'terrēre',         german:'erschrecken, in Schrecken versetzen' },
  { id:'l14_26', latin:'undique',         german:'von überall, überall, allseitig' },
  // Lektion 15
  { id:'l15_01', latin:'imperātor, -oris m',      german:'Feldherr, Kaiser' },
  { id:'l15_02', latin:'bellum, belli',     german:'der Krieg' },
  { id:'l15_03', latin:'pugnāre, pugno, pugnāvi',    german:'kämpfen' },
  { id:'l15_04', latin:'gēns, gentis f',   german:'das Geschlecht, der Stamm,das Volk' },
  { id:'l15_05', latin:'ferus, -a, -um',       german:'wild' },
  { id:'l15_06', latin:'barbarus, -a, -um',     german:'fremd; barbarisch; der Barbar' },
  { id:'l15_07', latin:'modus, modi m',     german:'die Art, die Weise; das Maß' },
  { id:'l15_08', latin:'cōnstat, cōnstiti',    german:'es steht fest, es ist bekannt' },
  { id:'l15_09', latin:'lēgātus, lēgāti m',        german:'der Gesandte, der Offizier, der Unterfeldherr' },
  { id:'l15_10', latin:'aliēnus, -a, -um',         german:'fremd' },
  { id:'l15_11', latin:'libertās, libertatis f',    german:'die Freiheit' },
  { id:'l15_12', latin:'māgnitudō, māgnitudinis f',    german:'Größe, Erhabenheit' },
  { id:'l15_13', latin:'corpus, corporis f',    german:'der Körper; der Leichnam' },
  { id:'l15_14', latin:'pectus, pectoris n',        german:'die Brust, das Herz' },
  { id:'l15_15', latin:'mirus, -a, -um',      german:'erstaunlich, sonderbar, wunderbar' },
  { id:'l15_16', latin:'incrēdibilis, incridibile',        german:'unglaublich' },
  { id:'l15_17', latin:'cōnfirmāre, cōnfirmo, cōnfirmavi',   german:'(be)kräftigen; ermutigen' },
  { id:'l15_18', latin:'nudus, -a, -um',        german:'nackt, bloß' },
  { id:'l15_19', latin:'negāre, nego, negāvi',    german:'leugnen; verweigern; (m. AcI) sagen, dass nicht' },
  { id:'l15_20', latin:'umquam',        german:'jemals' },
  { id:'l15_21', latin:'medius, -a, -um',     german:'der mittlere; mitten in…' },
  { id:'l15_22', latin:'putāre, puto, putāvi',    german:'glauben, meinen' },
  { id:'l15_23', latin:'litus, litoris n',  german:'die Küste, der Strand' },
  { id:'l15_24', latin:'mittere, mitto, misi',        german:'schicken, senden' },
  { id:'l15_25', latin:'ēgregius, -a, -um',     german:'hervorragend, ausgezeichnet' },
  { id:'l15_26', latin:'necesse est',      german:'es ist nötig / notwendig' },
  // Lektion 16
  { id:'l16_01', latin:'villa, villae f',      german:'die Villa, das Landhaus' },
  { id:'l16_02', latin:'rūs, rūris n',     german: 'das Land, das Feld' },
  { id:'l16_03', latin:'locus, loci m, loca, locōrum',    german: 'der Ort, der Platz, die Stelle' },
  { id:'l16_04', latin:'quiēscere, quiēscō, quievi',   german:'ruhen, sich ausruhen' },
  { id:'l16_05', latin:'negōtium, negōtii n',       german:'die Aufgabe; das Geschäft' },
  { id:'l16_06', latin:'ars, artis f',     german:'die Kunst; die Fähigkeit' },
  { id:'l16_07', latin:'novus, -a, -um',     german:'neu, neuartig' },
  { id:'l16_08', latin:'familiāris, familiārae',    german:'vertraut, verwandt, freundschaftl. –Vertrauter, Verwandter, Freund' },
  { id:'l16_09', latin:'meus, -a, -um',        german:'mein' },
  { id:'l16_10', latin:'tuus, -a, -um',         german:'dein' },
  { id:'l16_11', latin:'noster, nostra, nostrum',    german:'unser' },
  { id:'l16_12', latin:'vester, vestra, vestrum',    german:'euer' },
  { id:'l16_13', latin:'suus, -a, -um',    german:'sein, ihr' },
  { id:'l16_14', latin:'sē, sibi, sēcum',        german:'sich (Akk.), sich (Dat.), mit sich' },
  { id:'l16_15', latin:'mōns, montis m',      german:'der Berg' },
  { id:'l16_16', latin:'flūmen, flūminis n',        german:'der Fluss' },
  { id:'l16_17', latin:'arbor, arboris f',   german:'der Baum' },
  { id:'l16_18', latin:'avus, avi m',        german:'der Großvater' },
  { id:'l16_19', latin:'māiorēs, māiorum m (pl.)',    german:'die Vorfahren' },
  { id:'l16_20', latin:'quaesō/quaesumus',        german:'(ich) bitte/wir bitten' },
  { id:'l16_21', latin:'calamitās, calamitātis f',     german:'Unglück, Unheil; Schaden' },
  { id:'l16_22', latin:'accidere, áccidit, áccidit',    german:'geschehen, sich ereignen; zustoßen' },
  { id:'l16_23', latin:'cadere, cadō, cécidi',  german:'fallen' },
  { id:'l16_24', latin:'trahere, trahō, trāxi',        german:'ziehen, zerren, schleppen' },
  { id:'l16_25', latin:'nimis',     german:'zu, allzu' },
  { id:'l16_26', latin:'magis',      german:'mehr' },
  // Lektion 17
  { id:'l17_01', latin:'mulier, mulieris f',      german:'die (erwachsene) Frau' },
  { id:'l17_02', latin:'coniūnx, coniugis m/f',     german: 'der Ehemann/die Ehefrau' },
  { id:'l17_03', latin:'pāx, pācis f',    german: 'der Friede' },
  { id:'l17_04', latin:'asper, -a, -um',   german:'rau, grob, hart' },
  { id:'l17_05', latin:'facilis, facile',       german:'einfach, leicht, mühelos' },
  { id:'l17_06', latin:'oportet, oportui',     german:'es gehört sich, man muss' },
  { id:'l17_07', latin:'trīstis, trīste',     german:'traurig, düster' },
  { id:'l17_08', latin:'certāre, certō, certāvī',    german:'kämfen, streiten, wetteifern' },
  { id:'l17_09', latin:'placidus, -a, -um',        german: 'sanft, ruhig, friedlich' },
  { id:'l17_10', latin:'ōrnāre, ōrnō, ōrnāvī',         german:'schmücken; auszeichnen, ausstatten' },
  { id:'l17_11', latin:'nūbere, nūbo, nūpsī (m. Dat.)',    german:'(einen Mann) heiraten' },
  { id:'l17_12', latin:'velle, volō, voluī',    german:'wollen' },
  { id:'l17_13', latin:'nōlle, nōlō, nōluī',    german:'nicht wollen' },
  { id:'l17_14', latin:'mālle, mālō, māluī',        german:'lieber wollen' },
  { id:'l17_15', latin:'quam (bei Vergleichen)',      german:'als' },
  { id:'l17_16', latin:'quōmodo',        german:'wie; auf welche Weise' },
  { id:'l17_17', latin:'paucī, paucae, pauca',   german:'wenige' },
  { id:'l17_18', latin:'invītāre, invītō, invītāvi',        german:'einladen' },
  { id:'l17_19', latin:'celeber, celebris, celebre',    german:'viel besucht; gefeiert' },
  { id:'l17_20', latin:'equidem',        german:'(ich) allerdings, freilich' },
  { id:'l17_21', latin:'restāre, restō, restitī',     german:'übrig bleiben, Wiederstand leisten' },
  { id:'l17_22', latin:'interesse, intersum, interfuī',    german:'dazwischen sein; teilnehmen' },
  { id:'l17_23', latin:'at',  german:'aber, jedoch' },
  { id:'l17_24', latin:'cōgnōscere, cōgnōscō, cōgnōvī',     german:'kennenlernen, erkennen; erfahren; Perf. wissen, kennen' },
  { id:'l17_25', latin: 'marītus, marītī m',     german:'Der Ehemann' },
  // Lektion 18
// Lektion 18
  { id:'l18_01', latin:'sapientia, sapientiae',     german:'die Weisheit' },
  { id:'l18_02', latin:'disputāre, disputō, disputāvī',     german: 'diskutieren, sprechen über' },
  { id:'l18_03', latin:'beātus, -a, -um',     german: 'glücklich' },
  { id:'l18_04', latin:'honōs/honor, honōris m',     german:'die Ehre; das Ehrenamt' },
  { id:'l18_05', latin:'nōndum',     german:'noch nicht' },
  { id:'l18_06', latin:'rēctē (Adv.)',     german:'richtig, zu recht' },
  { id:'l18_07', latin:'sententia, sententiae f',     german:'der Satz; der Sinnspruch, die Meinung' },
  { id:'l18_08', latin:'probāre, probō, probāvī',     german:'billigen, gutheißen; prüfen' },
  { id:'l18_09', latin:'summus, -a, -um',     german: 'der Höchste, der Oberste; der Letzte' },
  { id:'l18_10', latin:'studium, studiī n',     german:'Bemühung, Streben; (wissenschaftliche) Beschäftigung' },
  { id:'l18_11', latin:'studēre',     german:'(m. Inf) sich bemühen(, zu tun), wünschen (, zu tun); (m. Dat.) sich beschäftigen mit, streben nach' },
  { id:'l18_12', latin:'gerere, gerō, gessī',     german: 'tragen; führen, ausführen' },
  { id:'l18_13', latin:'neque/nec',     german:'und nicht, auch nicht, aber nicht' },
  { id:'l18_14', latin:'quamquam',     german:'obwohl' },
  { id:'l18_15', latin:'sī',     german:'wenn, falls' },
  { id:'l18_16', latin:'quantus, -a, -um',     german:'wie groß, wie viel' },
  { id:'l18_17', latin:'quattuor',     german:'vier' },
  { id:'l18_18', latin:'quondam',     german:'einmal, einst' },
  { id:'l18_19', latin:'omnīnō',     german:'insgesamt, überhaupt, völlig' },
  { id:'l18_20', latin:'pūblicus, -a, -um',     german:'öffentlich, staatlich' },
  { id:'l18_21', latin:'providēre, provideō, providī',     german:'(m. Dat.) sorgen für; (m. Akk.) vorhersehen' },
  { id:'l18_22', latin:'perpetuus, -a, -um',     german:'ununterbrochen, dauerhaft, ewig' },
  { id:'l18_23', latin:'recēns, recentis',     german:'frisch, jung, neu' },
];
